<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Travel\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use NxSys\Library\Clients\Brex\API\Travel\Runtime\Normalizer\CheckArray;
use NxSys\Library\Clients\Brex\API\Travel\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class LodgingBookingDataReservationDetailsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'NxSys\\Library\\Clients\\Brex\\API\\Travel\\Model\\LodgingBookingDataReservationDetails';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'NxSys\\Library\\Clients\\Brex\\API\\Travel\\Model\\LodgingBookingDataReservationDetails';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \NxSys\Library\Clients\Brex\API\Travel\Model\LodgingBookingDataReservationDetails();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('confirmation_code', $data) && $data['confirmation_code'] !== null) {
            $object->setConfirmationCode($data['confirmation_code']);
            unset($data['confirmation_code']);
        } elseif (\array_key_exists('confirmation_code', $data) && $data['confirmation_code'] === null) {
            $object->setConfirmationCode(null);
        }
        if (\array_key_exists('check_in_time', $data)) {
            $object->setCheckInTime($this->denormalizer->denormalize($data['check_in_time'], 'NxSys\\Library\\Clients\\Brex\\API\\Travel\\Model\\LodgingBookingDataReservationDetailsCheckInTime', 'json', $context));
            unset($data['check_in_time']);
        }
        if (\array_key_exists('checkout_time', $data)) {
            $object->setCheckoutTime($this->denormalizer->denormalize($data['checkout_time'], 'NxSys\\Library\\Clients\\Brex\\API\\Travel\\Model\\LodgingBookingDataReservationDetailsCheckoutTime', 'json', $context));
            unset($data['checkout_time']);
        }
        if (\array_key_exists('room', $data)) {
            $object->setRoom($this->denormalizer->denormalize($data['room'], 'NxSys\\Library\\Clients\\Brex\\API\\Travel\\Model\\LodgingBookingDataReservationDetailsRoom', 'json', $context));
            unset($data['room']);
        }
        foreach ($data as $key => $value) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value;
            }
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if ($object->isInitialized('confirmationCode') && null !== $object->getConfirmationCode()) {
            $data['confirmation_code'] = $object->getConfirmationCode();
        }
        $data['check_in_time'] = $this->normalizer->normalize($object->getCheckInTime(), 'json', $context);
        $data['checkout_time'] = $this->normalizer->normalize($object->getCheckoutTime(), 'json', $context);
        if ($object->isInitialized('room') && null !== $object->getRoom()) {
            $data['room'] = $this->normalizer->normalize($object->getRoom(), 'json', $context);
        }
        foreach ($object as $key => $value) {
            if (preg_match('/.*/', (string) $key)) {
                $data[$key] = $value;
            }
        }

        return $data;
    }
}
