<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Transactions\Model;

class CardAccount extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * ID of the card account.
     *
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $status;
    /**
     * @var CardAccountCurrentBalance
     */
    protected $currentBalance;
    /**
     * @var CardAccountAvailableBalance
     */
    protected $availableBalance;
    /**
     * @var CardAccountAccountLimit
     */
    protected $accountLimit;
    /**
     * @var StatementPeriod
     */
    protected $currentStatementPeriod;

    /**
     * ID of the card account.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * ID of the card account.
     */
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }

    public function getCurrentBalance(): CardAccountCurrentBalance
    {
        return $this->currentBalance;
    }

    public function setCurrentBalance(CardAccountCurrentBalance $currentBalance): self
    {
        $this->initialized['currentBalance'] = true;
        $this->currentBalance = $currentBalance;

        return $this;
    }

    public function getAvailableBalance(): CardAccountAvailableBalance
    {
        return $this->availableBalance;
    }

    public function setAvailableBalance(CardAccountAvailableBalance $availableBalance): self
    {
        $this->initialized['availableBalance'] = true;
        $this->availableBalance = $availableBalance;

        return $this;
    }

    public function getAccountLimit(): CardAccountAccountLimit
    {
        return $this->accountLimit;
    }

    public function setAccountLimit(CardAccountAccountLimit $accountLimit): self
    {
        $this->initialized['accountLimit'] = true;
        $this->accountLimit = $accountLimit;

        return $this;
    }

    public function getCurrentStatementPeriod(): StatementPeriod
    {
        return $this->currentStatementPeriod;
    }

    public function setCurrentStatementPeriod(StatementPeriod $currentStatementPeriod): self
    {
        $this->initialized['currentStatementPeriod'] = true;
        $this->currentStatementPeriod = $currentStatementPeriod;

        return $this;
    }
}
