<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Transactions\Model;

class Statement extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $id;
    /**
     * @var StatementStartBalance
     */
    protected $startBalance;
    /**
     * @var StatementEndBalance
     */
    protected $endBalance;
    /**
     * @var StatementPeriod
     */
    protected $period;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getStartBalance(): StatementStartBalance
    {
        return $this->startBalance;
    }

    public function setStartBalance(StatementStartBalance $startBalance): self
    {
        $this->initialized['startBalance'] = true;
        $this->startBalance = $startBalance;

        return $this;
    }

    public function getEndBalance(): StatementEndBalance
    {
        return $this->endBalance;
    }

    public function setEndBalance(StatementEndBalance $endBalance): self
    {
        $this->initialized['endBalance'] = true;
        $this->endBalance = $endBalance;

        return $this;
    }

    public function getPeriod(): StatementPeriod
    {
        return $this->period;
    }

    public function setPeriod(StatementPeriod $period): self
    {
        $this->initialized['period'] = true;
        $this->period = $period;

        return $this;
    }
}
