<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Travel\Model;

class AirBookingDataFlightOperatingFlight extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The IATA code for the airline.
     *
     * @var string
     */
    protected $airlineCode;
    /**
     * The number of the flight.
     *
     * @var string
     */
    protected $number;
    /**
     * The name of the airline.
     *
     * @var string|null
     */
    protected $airlineName;

    /**
     * The IATA code for the airline.
     */
    public function getAirlineCode(): string
    {
        return $this->airlineCode;
    }

    /**
     * The IATA code for the airline.
     */
    public function setAirlineCode(string $airlineCode): self
    {
        $this->initialized['airlineCode'] = true;
        $this->airlineCode = $airlineCode;

        return $this;
    }

    /**
     * The number of the flight.
     */
    public function getNumber(): string
    {
        return $this->number;
    }

    /**
     * The number of the flight.
     */
    public function setNumber(string $number): self
    {
        $this->initialized['number'] = true;
        $this->number = $number;

        return $this;
    }

    /**
     * The name of the airline.
     */
    public function getAirlineName(): ?string
    {
        return $this->airlineName;
    }

    /**
     * The name of the airline.
     */
    public function setAirlineName(?string $airlineName): self
    {
        $this->initialized['airlineName'] = true;
        $this->airlineName = $airlineName;

        return $this;
    }
}
