<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Travel\Model;

class AirBookingDataFlight extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The place where a flight departs from or arrives at.
     *
     * @var AirBookingDataFlightEndpoint
     */
    protected $origin;
    /**
     * The place where a flight departs from or arrives at.
     *
     * @var AirBookingDataFlightEndpoint
     */
    protected $destination;
    /**
     * @var AirBookingDataFlightDepartureTime
     */
    protected $departureTime;
    /**
     * @var AirBookingDataFlightArrivalTime
     */
    protected $arrivalTime;
    /**
     * The duration of the flight in the ISO 8601 PnYnMnDTnHnMnS format.
     *
     * @var string|null
     */
    protected $duration;
    /**
     * The airline confirmation code.
     *
     * @var string|null
     */
    protected $confirmationCode;
    /**
     * @var string
     */
    protected $cabinClass;
    /**
     * @var AirBookingDataFlightMarketingFlight
     */
    protected $marketingFlight;
    /**
     * @var AirBookingDataFlightOperatingFlight
     */
    protected $operatingFlight;
    /**
     * @var AirBookingDataFlightSeat
     */
    protected $seat;

    /**
     * The place where a flight departs from or arrives at.
     */
    public function getOrigin(): AirBookingDataFlightEndpoint
    {
        return $this->origin;
    }

    /**
     * The place where a flight departs from or arrives at.
     */
    public function setOrigin(AirBookingDataFlightEndpoint $origin): self
    {
        $this->initialized['origin'] = true;
        $this->origin = $origin;

        return $this;
    }

    /**
     * The place where a flight departs from or arrives at.
     */
    public function getDestination(): AirBookingDataFlightEndpoint
    {
        return $this->destination;
    }

    /**
     * The place where a flight departs from or arrives at.
     */
    public function setDestination(AirBookingDataFlightEndpoint $destination): self
    {
        $this->initialized['destination'] = true;
        $this->destination = $destination;

        return $this;
    }

    public function getDepartureTime(): AirBookingDataFlightDepartureTime
    {
        return $this->departureTime;
    }

    public function setDepartureTime(AirBookingDataFlightDepartureTime $departureTime): self
    {
        $this->initialized['departureTime'] = true;
        $this->departureTime = $departureTime;

        return $this;
    }

    public function getArrivalTime(): AirBookingDataFlightArrivalTime
    {
        return $this->arrivalTime;
    }

    public function setArrivalTime(AirBookingDataFlightArrivalTime $arrivalTime): self
    {
        $this->initialized['arrivalTime'] = true;
        $this->arrivalTime = $arrivalTime;

        return $this;
    }

    /**
     * The duration of the flight in the ISO 8601 PnYnMnDTnHnMnS format.
     */
    public function getDuration(): ?string
    {
        return $this->duration;
    }

    /**
     * The duration of the flight in the ISO 8601 PnYnMnDTnHnMnS format.
     */
    public function setDuration(?string $duration): self
    {
        $this->initialized['duration'] = true;
        $this->duration = $duration;

        return $this;
    }

    /**
     * The airline confirmation code.
     */
    public function getConfirmationCode(): ?string
    {
        return $this->confirmationCode;
    }

    /**
     * The airline confirmation code.
     */
    public function setConfirmationCode(?string $confirmationCode): self
    {
        $this->initialized['confirmationCode'] = true;
        $this->confirmationCode = $confirmationCode;

        return $this;
    }

    public function getCabinClass(): string
    {
        return $this->cabinClass;
    }

    public function setCabinClass(string $cabinClass): self
    {
        $this->initialized['cabinClass'] = true;
        $this->cabinClass = $cabinClass;

        return $this;
    }

    public function getMarketingFlight(): AirBookingDataFlightMarketingFlight
    {
        return $this->marketingFlight;
    }

    public function setMarketingFlight(AirBookingDataFlightMarketingFlight $marketingFlight): self
    {
        $this->initialized['marketingFlight'] = true;
        $this->marketingFlight = $marketingFlight;

        return $this;
    }

    public function getOperatingFlight(): AirBookingDataFlightOperatingFlight
    {
        return $this->operatingFlight;
    }

    public function setOperatingFlight(AirBookingDataFlightOperatingFlight $operatingFlight): self
    {
        $this->initialized['operatingFlight'] = true;
        $this->operatingFlight = $operatingFlight;

        return $this;
    }

    public function getSeat(): AirBookingDataFlightSeat
    {
        return $this->seat;
    }

    public function setSeat(AirBookingDataFlightSeat $seat): self
    {
        $this->initialized['seat'] = true;
        $this->seat = $seat;

        return $this;
    }
}
