<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Travel\Model;

class LodgingBookingData extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Information on a lodging venue.
     *
     * @var LodgingBookingDataLodgingDetails
     */
    protected $lodgingDetails;
    /**
     * Information on a reservation such as check-in, checkout, etc.
     *
     * @var LodgingBookingDataReservationDetails
     */
    protected $reservationDetails;
    /**
     * @var string
     */
    protected $type;

    /**
     * Information on a lodging venue.
     */
    public function getLodgingDetails(): LodgingBookingDataLodgingDetails
    {
        return $this->lodgingDetails;
    }

    /**
     * Information on a lodging venue.
     */
    public function setLodgingDetails(LodgingBookingDataLodgingDetails $lodgingDetails): self
    {
        $this->initialized['lodgingDetails'] = true;
        $this->lodgingDetails = $lodgingDetails;

        return $this;
    }

    /**
     * Information on a reservation such as check-in, checkout, etc.
     */
    public function getReservationDetails(): LodgingBookingDataReservationDetails
    {
        return $this->reservationDetails;
    }

    /**
     * Information on a reservation such as check-in, checkout, etc.
     */
    public function setReservationDetails(LodgingBookingDataReservationDetails $reservationDetails): self
    {
        $this->initialized['reservationDetails'] = true;
        $this->reservationDetails = $reservationDetails;

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }
}
