<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Travel\Model;

class LodgingBookingDataLodgingDetails extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The name of the venue as displayed to the user.
     *
     * @var string
     */
    protected $displayName;
    /**
     * @var LodgingBookingDataLodgingDetailsContactInformation
     */
    protected $contactInformation;
    /**
     * The star rating of the hotel. Some hotels have half stars.
     *
     * @var float|null
     */
    protected $starRating;
    /**
     * The brand name of the hotel.
     *
     * @var string|null
     */
    protected $brandName;
    /**
     * The name of the hotel chain.
     *
     * @var string|null
     */
    protected $chainName;
    /**
     * @var LodgingBookingDataLodgingDetailsLocation
     */
    protected $location;

    /**
     * The name of the venue as displayed to the user.
     */
    public function getDisplayName(): string
    {
        return $this->displayName;
    }

    /**
     * The name of the venue as displayed to the user.
     */
    public function setDisplayName(string $displayName): self
    {
        $this->initialized['displayName'] = true;
        $this->displayName = $displayName;

        return $this;
    }

    public function getContactInformation(): LodgingBookingDataLodgingDetailsContactInformation
    {
        return $this->contactInformation;
    }

    public function setContactInformation(LodgingBookingDataLodgingDetailsContactInformation $contactInformation): self
    {
        $this->initialized['contactInformation'] = true;
        $this->contactInformation = $contactInformation;

        return $this;
    }

    /**
     * The star rating of the hotel. Some hotels have half stars.
     */
    public function getStarRating(): ?float
    {
        return $this->starRating;
    }

    /**
     * The star rating of the hotel. Some hotels have half stars.
     */
    public function setStarRating(?float $starRating): self
    {
        $this->initialized['starRating'] = true;
        $this->starRating = $starRating;

        return $this;
    }

    /**
     * The brand name of the hotel.
     */
    public function getBrandName(): ?string
    {
        return $this->brandName;
    }

    /**
     * The brand name of the hotel.
     */
    public function setBrandName(?string $brandName): self
    {
        $this->initialized['brandName'] = true;
        $this->brandName = $brandName;

        return $this;
    }

    /**
     * The name of the hotel chain.
     */
    public function getChainName(): ?string
    {
        return $this->chainName;
    }

    /**
     * The name of the hotel chain.
     */
    public function setChainName(?string $chainName): self
    {
        $this->initialized['chainName'] = true;
        $this->chainName = $chainName;

        return $this;
    }

    public function getLocation(): LodgingBookingDataLodgingDetailsLocation
    {
        return $this->location;
    }

    public function setLocation(LodgingBookingDataLodgingDetailsLocation $location): self
    {
        $this->initialized['location'] = true;
        $this->location = $location;

        return $this;
    }
}
