<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Team\Normalizer;

use NxSys\Library\Clients\Brex\API\Team\Runtime\Normalizer\CheckArray;
use NxSys\Library\Clients\Brex\API\Team\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class JaneObjectNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;
        protected $normalizers = [
            \NxSys\Library\Clients\Brex\API\Team\Model\Address::class => AddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\Card::class => CardNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardSpendControls::class => CardSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardMailingAddress::class => CardMailingAddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardAttributePreferences::class => CardAttributePreferencesNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardExpiration::class => CardExpirationNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardNumberResponse::class => CardNumberResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CompanyResponse::class => CompanyResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequest::class => CreateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestSpendControls::class => CreateCardRequestSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestMailingAddress::class => CreateCardRequestMailingAddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestCardAttributePreferences::class => CreateCardRequestCardAttributePreferencesNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateDepartmentRequest::class => CreateDepartmentRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateLocationRequest::class => CreateLocationRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateUserRequest::class => CreateUserRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\DepartmentResponse::class => DepartmentResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\LocationResponse::class => LocationResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\LockCardRequest::class => LockCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\Money::class => MoneyNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageCard::class => PageCardNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageDepartmentResponse::class => PageDepartmentResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageLocationResponse::class => PageLocationResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageUserResponse::class => PageUserResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SecureEmailForCardDetailsRequest::class => SecureEmailForCardDetailsRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequest::class => SetUserLimitRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequestMonthlyLimit::class => SetUserLimitRequestMonthlyLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControl::class => SpendControlNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlRequest::class => SpendControlRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequest::class => SpendControlUpdateRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequestSpendLimit::class => SpendControlUpdateRequestSpendLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\TerminateCardRequest::class => TerminateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequest::class => UpdateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequestSpendControls::class => UpdateCardRequestSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateUserRequest::class => UpdateUserRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponse::class => UserLimitResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyLimit::class => UserLimitResponseMonthlyLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyAvailable::class => UserLimitResponseMonthlyAvailableNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserOwner::class => UserOwnerNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserResponse::class => UserResponseNormalizer::class,

            \Jane\Component\JsonSchemaRuntime\Reference::class => \NxSys\Library\Clients\Brex\API\Team\Runtime\Normalizer\ReferenceNormalizer::class,
        ];
        protected $normalizersCache = [];

        public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
        {
            return array_key_exists($type, $this->normalizers);
        }

        public function supportsNormalization($data, $format = null, array $context = []): bool
        {
            return is_object($data) && array_key_exists(get_class($data), $this->normalizers);
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $normalizerClass = $this->normalizers[get_class($object)];
            $normalizer = $this->getNormalizer($normalizerClass);

            return $normalizer->normalize($object, $format, $context);
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            $denormalizerClass = $this->normalizers[$type];
            $denormalizer = $this->getNormalizer($denormalizerClass);

            return $denormalizer->denormalize($data, $type, $format, $context);
        }

        private function getNormalizer(string $normalizerClass)
        {
            return $this->normalizersCache[$normalizerClass] ?? $this->initNormalizer($normalizerClass);
        }

        private function initNormalizer(string $normalizerClass)
        {
            $normalizer = new $normalizerClass();
            $normalizer->setNormalizer($this->normalizer);
            $normalizer->setDenormalizer($this->denormalizer);
            $this->normalizersCache[$normalizerClass] = $normalizer;

            return $normalizer;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [
                \NxSys\Library\Clients\Brex\API\Team\Model\Address::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\Card::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardMailingAddress::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardAttributePreferences::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardExpiration::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardNumberResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CompanyResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestMailingAddress::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestCardAttributePreferences::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateDepartmentRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateLocationRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateUserRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\DepartmentResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\LocationResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\LockCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\Money::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageCard::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageDepartmentResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageLocationResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageUserResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SecureEmailForCardDetailsRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequestMonthlyLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControl::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequestSpendLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\TerminateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequestSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateUserRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyAvailable::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserOwner::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserResponse::class => false,
                \Jane\Component\JsonSchemaRuntime\Reference::class => false,
            ];
        }
    }
} else {
    class JaneObjectNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;
        protected $normalizers = [
            \NxSys\Library\Clients\Brex\API\Team\Model\Address::class => AddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\Card::class => CardNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardSpendControls::class => CardSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardMailingAddress::class => CardMailingAddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardAttributePreferences::class => CardAttributePreferencesNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardExpiration::class => CardExpirationNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CardNumberResponse::class => CardNumberResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CompanyResponse::class => CompanyResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequest::class => CreateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestSpendControls::class => CreateCardRequestSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestMailingAddress::class => CreateCardRequestMailingAddressNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestCardAttributePreferences::class => CreateCardRequestCardAttributePreferencesNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateDepartmentRequest::class => CreateDepartmentRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateLocationRequest::class => CreateLocationRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\CreateUserRequest::class => CreateUserRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\DepartmentResponse::class => DepartmentResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\LocationResponse::class => LocationResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\LockCardRequest::class => LockCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\Money::class => MoneyNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageCard::class => PageCardNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageDepartmentResponse::class => PageDepartmentResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageLocationResponse::class => PageLocationResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\PageUserResponse::class => PageUserResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SecureEmailForCardDetailsRequest::class => SecureEmailForCardDetailsRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequest::class => SetUserLimitRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequestMonthlyLimit::class => SetUserLimitRequestMonthlyLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControl::class => SpendControlNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlRequest::class => SpendControlRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequest::class => SpendControlUpdateRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequestSpendLimit::class => SpendControlUpdateRequestSpendLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\TerminateCardRequest::class => TerminateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequest::class => UpdateCardRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequestSpendControls::class => UpdateCardRequestSpendControlsNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UpdateUserRequest::class => UpdateUserRequestNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponse::class => UserLimitResponseNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyLimit::class => UserLimitResponseMonthlyLimitNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyAvailable::class => UserLimitResponseMonthlyAvailableNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserOwner::class => UserOwnerNormalizer::class,

            \NxSys\Library\Clients\Brex\API\Team\Model\UserResponse::class => UserResponseNormalizer::class,

            \Jane\Component\JsonSchemaRuntime\Reference::class => \NxSys\Library\Clients\Brex\API\Team\Runtime\Normalizer\ReferenceNormalizer::class,
        ];
        protected $normalizersCache = [];

        public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
        {
            return array_key_exists($type, $this->normalizers);
        }

        public function supportsNormalization($data, $format = null, array $context = []): bool
        {
            return is_object($data) && array_key_exists(get_class($data), $this->normalizers);
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $normalizerClass = $this->normalizers[get_class($object)];
            $normalizer = $this->getNormalizer($normalizerClass);

            return $normalizer->normalize($object, $format, $context);
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            $denormalizerClass = $this->normalizers[$type];
            $denormalizer = $this->getNormalizer($denormalizerClass);

            return $denormalizer->denormalize($data, $type, $format, $context);
        }

        private function getNormalizer(string $normalizerClass)
        {
            return $this->normalizersCache[$normalizerClass] ?? $this->initNormalizer($normalizerClass);
        }

        private function initNormalizer(string $normalizerClass)
        {
            $normalizer = new $normalizerClass();
            $normalizer->setNormalizer($this->normalizer);
            $normalizer->setDenormalizer($this->denormalizer);
            $this->normalizersCache[$normalizerClass] = $normalizer;

            return $normalizer;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [
                \NxSys\Library\Clients\Brex\API\Team\Model\Address::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\Card::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardMailingAddress::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardAttributePreferences::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardExpiration::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CardNumberResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CompanyResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestMailingAddress::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateCardRequestCardAttributePreferences::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateDepartmentRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateLocationRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\CreateUserRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\DepartmentResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\LocationResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\LockCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\Money::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageCard::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageDepartmentResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageLocationResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\PageUserResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SecureEmailForCardDetailsRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SetUserLimitRequestMonthlyLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControl::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\SpendControlUpdateRequestSpendLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\TerminateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateCardRequestSpendControls::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UpdateUserRequest::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponse::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyLimit::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserLimitResponseMonthlyAvailable::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserOwner::class => false,
                \NxSys\Library\Clients\Brex\API\Team\Model\UserResponse::class => false,
                \Jane\Component\JsonSchemaRuntime\Reference::class => false,
            ];
        }
    }
}
