<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Team\Exception;

class UpdateUserBadRequestException extends BadRequestException
{
    public function __construct()
    {
        parent::__construct('Bad request');
    }
}
