<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Webhooks\Model;

class ProductApplication extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Application status of a product.

     *
     * @var string
     */
    protected $cash;

    /**
     * Application status of a product.

    `CLOSED` - The product account is closed.
     */
    public function getCash(): string
    {
        return $this->cash;
    }

    /**
     * Application status of a product.

    `CLOSED` - The product account is closed.
     */
    public function setCash(string $cash): self
    {
        $this->initialized['cash'] = true;
        $this->cash = $cash;

        return $this;
    }
}
