<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Payments\Normalizer;

use Jane\Component\JsonSchemaRuntime\Reference;
use NxSys\Library\Clients\Brex\API\Payments\Runtime\Normalizer\CheckArray;
use NxSys\Library\Clients\Brex\API\Payments\Runtime\Normalizer\ValidatorTrait;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

if (!class_exists(Kernel::class) or (Kernel::MAJOR_VERSION >= 7 or Kernel::MAJOR_VERSION === 6 and Kernel::MINOR_VERSION === 4)) {
    class BankAccountDetailsResponseNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization(mixed $data, string $type, ?string $format = null, array $context = []): bool
        {
            return $type === \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class;
        }

        public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('type', $data)) {
                $object->setType($data['type']);
                unset($data['type']);
            }
            if (\array_key_exists('routing_number', $data) && $data['routing_number'] !== null) {
                $object->setRoutingNumber($data['routing_number']);
                unset($data['routing_number']);
            } elseif (\array_key_exists('routing_number', $data) && $data['routing_number'] === null) {
                $object->setRoutingNumber(null);
            }
            if (\array_key_exists('account_number', $data) && $data['account_number'] !== null) {
                $object->setAccountNumber($data['account_number']);
                unset($data['account_number']);
            } elseif (\array_key_exists('account_number', $data) && $data['account_number'] === null) {
                $object->setAccountNumber(null);
            }
            if (\array_key_exists('description', $data) && $data['description'] !== null) {
                $object->setDescription($data['description']);
                unset($data['description']);
            } elseif (\array_key_exists('description', $data) && $data['description'] === null) {
                $object->setDescription(null);
            }
            if (\array_key_exists('beneficiary_bank', $data)) {
                $object->setBeneficiaryBank($this->denormalizer->denormalize($data['beneficiary_bank'], \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponsebeneficiaryBank::class, 'json', $context));
                unset($data['beneficiary_bank']);
            }
            if (\array_key_exists('fed_reference_number', $data) && $data['fed_reference_number'] !== null) {
                $object->setFedReferenceNumber($data['fed_reference_number']);
                unset($data['fed_reference_number']);
            } elseif (\array_key_exists('fed_reference_number', $data) && $data['fed_reference_number'] === null) {
                $object->setFedReferenceNumber(null);
            }
            if (\array_key_exists('external_memo', $data) && $data['external_memo'] !== null) {
                $object->setExternalMemo($data['external_memo']);
                unset($data['external_memo']);
            } elseif (\array_key_exists('external_memo', $data) && $data['external_memo'] === null) {
                $object->setExternalMemo(null);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
        {
            $data = [];
            $data['type'] = $object->getType();
            if ($object->isInitialized('routingNumber') && null !== $object->getRoutingNumber()) {
                $data['routing_number'] = $object->getRoutingNumber();
            }
            if ($object->isInitialized('accountNumber') && null !== $object->getAccountNumber()) {
                $data['account_number'] = $object->getAccountNumber();
            }
            if ($object->isInitialized('description') && null !== $object->getDescription()) {
                $data['description'] = $object->getDescription();
            }
            if ($object->isInitialized('beneficiaryBank') && null !== $object->getBeneficiaryBank()) {
                $data['beneficiary_bank'] = $this->normalizer->normalize($object->getBeneficiaryBank(), 'json', $context);
            }
            if ($object->isInitialized('fedReferenceNumber') && null !== $object->getFedReferenceNumber()) {
                $data['fed_reference_number'] = $object->getFedReferenceNumber();
            }
            if ($object->isInitialized('externalMemo') && null !== $object->getExternalMemo()) {
                $data['external_memo'] = $object->getExternalMemo();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class => false];
        }
    }
} else {
    class BankAccountDetailsResponseNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
    {
        use DenormalizerAwareTrait;
        use NormalizerAwareTrait;
        use CheckArray;
        use ValidatorTrait;

        public function supportsDenormalization($data, $type, ?string $format = null, array $context = []): bool
        {
            return $type === \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class;
        }

        public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
        {
            return is_object($data) && get_class($data) === \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class;
        }

        public function denormalize($data, $type, $format = null, array $context = [])
        {
            if (isset($data['$ref'])) {
                return new Reference($data['$ref'], $context['document-origin']);
            }
            if (isset($data['$recursiveRef'])) {
                return new Reference($data['$recursiveRef'], $context['document-origin']);
            }
            $object = new \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse();
            if (null === $data || false === \is_array($data)) {
                return $object;
            }
            if (\array_key_exists('type', $data)) {
                $object->setType($data['type']);
                unset($data['type']);
            }
            if (\array_key_exists('routing_number', $data) && $data['routing_number'] !== null) {
                $object->setRoutingNumber($data['routing_number']);
                unset($data['routing_number']);
            } elseif (\array_key_exists('routing_number', $data) && $data['routing_number'] === null) {
                $object->setRoutingNumber(null);
            }
            if (\array_key_exists('account_number', $data) && $data['account_number'] !== null) {
                $object->setAccountNumber($data['account_number']);
                unset($data['account_number']);
            } elseif (\array_key_exists('account_number', $data) && $data['account_number'] === null) {
                $object->setAccountNumber(null);
            }
            if (\array_key_exists('description', $data) && $data['description'] !== null) {
                $object->setDescription($data['description']);
                unset($data['description']);
            } elseif (\array_key_exists('description', $data) && $data['description'] === null) {
                $object->setDescription(null);
            }
            if (\array_key_exists('beneficiary_bank', $data)) {
                $object->setBeneficiaryBank($this->denormalizer->denormalize($data['beneficiary_bank'], \NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponsebeneficiaryBank::class, 'json', $context));
                unset($data['beneficiary_bank']);
            }
            if (\array_key_exists('fed_reference_number', $data) && $data['fed_reference_number'] !== null) {
                $object->setFedReferenceNumber($data['fed_reference_number']);
                unset($data['fed_reference_number']);
            } elseif (\array_key_exists('fed_reference_number', $data) && $data['fed_reference_number'] === null) {
                $object->setFedReferenceNumber(null);
            }
            if (\array_key_exists('external_memo', $data) && $data['external_memo'] !== null) {
                $object->setExternalMemo($data['external_memo']);
                unset($data['external_memo']);
            } elseif (\array_key_exists('external_memo', $data) && $data['external_memo'] === null) {
                $object->setExternalMemo(null);
            }
            foreach ($data as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $object[$key] = $value;
                }
            }

            return $object;
        }

        /**
         * @return array|string|int|float|bool|\ArrayObject|null
         */
        public function normalize($object, $format = null, array $context = [])
        {
            $data = [];
            $data['type'] = $object->getType();
            if ($object->isInitialized('routingNumber') && null !== $object->getRoutingNumber()) {
                $data['routing_number'] = $object->getRoutingNumber();
            }
            if ($object->isInitialized('accountNumber') && null !== $object->getAccountNumber()) {
                $data['account_number'] = $object->getAccountNumber();
            }
            if ($object->isInitialized('description') && null !== $object->getDescription()) {
                $data['description'] = $object->getDescription();
            }
            if ($object->isInitialized('beneficiaryBank') && null !== $object->getBeneficiaryBank()) {
                $data['beneficiary_bank'] = $this->normalizer->normalize($object->getBeneficiaryBank(), 'json', $context);
            }
            if ($object->isInitialized('fedReferenceNumber') && null !== $object->getFedReferenceNumber()) {
                $data['fed_reference_number'] = $object->getFedReferenceNumber();
            }
            if ($object->isInitialized('externalMemo') && null !== $object->getExternalMemo()) {
                $data['external_memo'] = $object->getExternalMemo();
            }
            foreach ($object as $key => $value) {
                if (preg_match('/.*/', (string) $key)) {
                    $data[$key] = $value;
                }
            }

            return $data;
        }

        public function getSupportedTypes(?string $format = null): array
        {
            return [\NxSys\Library\Clients\Brex\API\Payments\Model\BankAccountDetailsResponse::class => false];
        }
    }
}
