<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Team\Model;

class CardNumberResponse extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $number;
    /**
     * @var string
     */
    protected $cvv;
    /**
     * Card expiration year and month. Cards expire on the last day of the expiration month.
     *
     * The expiration date is in UTC for cards starting with 555671, 428803 and 485932.
     * And the expiration date is in PST for cards starting with 511572.
     *
     * @var CardExpiration
     */
    protected $expirationDate;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getNumber(): string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->initialized['number'] = true;
        $this->number = $number;

        return $this;
    }

    public function getCvv(): string
    {
        return $this->cvv;
    }

    public function setCvv(string $cvv): self
    {
        $this->initialized['cvv'] = true;
        $this->cvv = $cvv;

        return $this;
    }

    /**
     * Card expiration year and month. Cards expire on the last day of the expiration month.
     *
     * The expiration date is in UTC for cards starting with 555671, 428803 and 485932.
     * And the expiration date is in PST for cards starting with 511572.
     */
    public function getExpirationDate(): CardExpiration
    {
        return $this->expirationDate;
    }

    /**
     * Card expiration year and month. Cards expire on the last day of the expiration month.
     *
     * The expiration date is in UTC for cards starting with 555671, 428803 and 485932.
     * And the expiration date is in PST for cards starting with 511572.
     */
    public function setExpirationDate(CardExpiration $expirationDate): self
    {
        $this->initialized['expirationDate'] = true;
        $this->expirationDate = $expirationDate;

        return $this;
    }
}
