<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Team\Model;

class CardAttributePreferences extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string
     */
    protected $threeDomainSecureEnabledPreference;

    public function getThreeDomainSecureEnabledPreference(): string
    {
        return $this->threeDomainSecureEnabledPreference;
    }

    public function setThreeDomainSecureEnabledPreference(string $threeDomainSecureEnabledPreference): self
    {
        $this->initialized['threeDomainSecureEnabledPreference'] = true;
        $this->threeDomainSecureEnabledPreference = $threeDomainSecureEnabledPreference;

        return $this;
    }
}
