<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace NxSys\Library\Clients\Brex\API\Team\Model;

class CreateDepartmentRequest extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Name of the department.
     *
     * @var string
     */
    protected $name;
    /**
     * Description of the department.
     *
     * @var string|null
     */
    protected $description;

    /**
     * Name of the department.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Name of the department.
     */
    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * Description of the department.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Description of the department.
     */
    public function setDescription(?string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }
}
